# 📌 Instructions for NumPy and Pandas Hands-on Exercises

1. **All challenges or Tasks are compulsory.**  
   You must complete all the NumPy and Pandas exercises. Do not skip any challenge.

2. **Write your own Python code.**  
   Use the concepts and functions taught in the class to solve each problem.

3. **Run every code cell.**  
   Make sure your code executes successfully and the required output is visible.

4. **Do not hard-code answers.**  
   Your program should calculate the answer. For example, do not manually write the name of the top-performing student. Use NumPy/Pandas to find it.

5. **Use the concepts taught in class.**  
   Try to solve the problems using NumPy arrays, indexing, slicing, array operations, Boolean filtering, Pandas DataFrames, column selection, filtering, sorting, and other concepts discussed in the sessions.

6. **Understand your code.**  
   You should be able to explain what your code does and why you used a particular function or operation.

7. **Do not copy-paste solutions from others.**  
   You may refer to examples discussed in class, but solve the exercises independently.

8. **Check your output carefully.**  
   If the output looks incorrect, check your code and try to identify and fix the problem.



09. **Before submitting, make sure that:**
    - All NumPy challenges are completed.
    - All Pandas challenges are completed.
    - All code cells have been executed.
    - Required outputs are visible.
    - There are no unresolved errors.
    - You can explain your solutions.

11. **Save and Submit Your Notebook.**  
    Save your notebook file using your **Roll Number** as the filename.  
    For example: `AIDE2026_001.ipynb`

    After completing the exercises, **submit the notebook file on Google Classroom**.

### 🎯 Objective

The objective of these exercises is **not only to get the correct output**, but to learn how to use **NumPy and Pandas to solve real-world data problems using Python.**

# Real life Problem
## Suppose we have a marks of 10 students. We want to perform the following operation
* Calculate the average
* Add 5 marks to everyone, find the highest mark
* Find how many students scored above 50

In [354]:
marks=[45, 67, 32, 89,56, 72, 41, 90, 63, 55]

### How would you calculate the average?

In [355]:
sum(marks)/len(marks)

61.0

## Challenges
* Don't you think that this is little complicated
* To overcome this, numpy has been introduced.

In [356]:
import numpy as np

marks=[45, 67, 32, 89,56, 72, 41, 90, 63, 55]
marks=np.array([marks])
print(marks)

[[45 67 32 89 56 72 41 90 63 55]]

# 2. Activity 1- Creating Numpy Arrays

In [357]:
import numpy as np
a=np.array([10,20,30,40,50])

print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>

In [358]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(5,)
1
5
int64

# 3. Activity 2- Numpy vs Python List

In [359]:
marks = [40,50,60,70]

In [360]:
marks

[40, 50, 60, 70]

In [361]:
marks=np.array([40,50,60,70])
print(marks+5)

[45 55 65 75]

### Numpy allows us to perform the same mathematical operations on the entire array

# Activity 3- Basic Mathematical Operations

In [362]:
prices=np.array([100,200,300,400,500])

**Add Rs 50**

In [363]:
prices+50

array([150, 250, 350, 450, 550])

**10% Discount**

In [364]:
prices*.90

array([ 90., 180., 270., 360., 450.])

**Double the price**

In [365]:
prices*2

array([ 200,  400,  600,  800, 1000])

**Divide by 2**

In [366]:
prices/2

array([ 50., 100., 150., 200., 250.])

**Square**

In [367]:
prices**2

array([ 10000,  40000,  90000, 160000, 250000])

# Activity 4- Important Statistical Functions

In [368]:
marks=np.array([45,67,32,89,56,72,41,90,63,55])

**Average**

In [369]:
marks.mean()

np.float64(61.0)

**Maximum**

In [370]:
marks.max()

np.int64(90)

**Minimum**

In [371]:
marks.min()

np.int64(32)

**Total**

In [372]:
marks.sum()

np.int64(610)

**Standard Deviation**

In [373]:
marks.std()

np.float64(18.286607121059937)

**Median**

In [374]:
np.median(marks)

np.float64(59.5)

**Find the difference between the highest and lowest marks**

# Activity 5- Indexing and Slicing

In [375]:
marks=np.array([45,67,32,89,56,72,41,90,63,55])

**What is the first mark?**

In [376]:
marks[0]

np.int64(45)

**What is the last mark?**

In [377]:
marks[-1]

np.int64(55)

**First three marks?**

In [378]:
marks[:3]

array([45, 67, 32])

**Marks from position 3 to 6?**

In [379]:
marks[3:7]

array([89, 56, 72, 41])

**Every second mark?**

In [380]:
marks[::2]

array([45, 32, 56, 41, 63])

# Activity 6-Boolean Filtering

In [381]:
marks=np.array([45,67,32,89,56,72,41,90,90,63,55])

**Which students scored more than 60?***

In [382]:
marks>60

array([False,  True, False,  True, False,  True, False,  True,  True,
        True, False])

In [383]:
marks[marks>60]

array([67, 89, 72, 90, 90, 63])

# Activity 7-2D Arrays

In [384]:
marks=np.array([
    [80,70,89],
    [20,40,90],
    [30,48,89],
    [55,89,58]
])

In [385]:
print(marks.shape)

(4, 3)

**First student's marks?**

In [386]:
marks[:,0]

array([80, 20, 30, 55])

**Fist subject's marks**

In [387]:
marks[0,0]

np.int64(80)

# Activity 8- Row and Column Calculations

In [388]:
marks.mean(axis=0)

array([46.25, 61.75, 81.5 ])

In [389]:
marks.mean(axis=1)

array([79.66666667, 50.        , 55.66666667, 67.33333333])

# Mini-Project-1 Student Marks Analyzer

## Dataset

In [390]:
import numpy as np

In [391]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 70, 72],
    [88, 92, 95],
    [55, 60, 58],
    [92, 89, 94]
])

Assume:
* Each row represents one student
* Columns represent Python, Maths, and AI, respectively
* Each subject is out of 100

## Task 1: Task 1 — Understand the Dataset
Find
* Number of students
* Number of subjects
* Total number of marks

In [392]:
marks = np.array([
    [78, 85, 90],
    [65, 70, 72],
    [88, 92, 95],
    [55, 60, 58],
    [92, 89, 94]
])

print("No. of students:",len(marks))
print("No. of subjects:",len(marks[0]))
print("Total number of marks:",marks.sum())

No. of students: 5
No. of subjects: 3
Total number of marks: 1183

## Task 2: Subject-wise Analysis
Find the average marks in each subject.
Your output should tell you:
* Average Python marks:?
* Average Maths marks:?
* Average AI marks:?

In [393]:
print("Average marks of Python:",marks.mean(axis=0)[0])
print("Average marks of Maths:",marks[:,1].mean())
print("Average marks of AI:",marks[:,2].mean())

Average marks of Python: 75.6
Average marks of Maths: 79.2
Average marks of AI: 81.8

# Task 3: Student-wise Analysis
Find the average marks of every student.
Expected output:
* student 1:?
* student 2:?
* Student 3:?
* Student 4:?
* Student 5:?

In [394]:
for i in range (0,len(marks)) :
  print(f"Average marks of Student{i+1} : {marks.mean(axis=1)[i]}")

Average marks of Student1 : 84.33333333333333
Average marks of Student2 : 69.0
Average marks of Student3 : 91.66666666666667
Average marks of Student4 : 57.666666666666664
Average marks of Student5 : 91.66666666666667

# Task 4: Find the Top Performer
Find the student who has the highest average marks.
Also find the student's average

In [395]:
a = list(marks.sum(axis=1))
print("The student with highest average marks:",a.index(max(a))+1)

The student with highest average marks: 3

# Task 5: Find the Weakest Performer
Find the student who has the lowest average marks.

Also find the student's average

In [396]:
print("The student with highest average marks:",a.index(min(a))+1,"and the students average marks is",marks[3,:].mean())

The student with highest average marks: 4 and the students average marks is 57.666666666666664

# Task 6: Students Who Performed Well
Find all students whose marks are greater than 75.
Don't manually check each student.
* Use Boolean filtering

In [397]:
a = np.array(marks.mean(axis=1))
b = list(a[a > 75])
c = []
d = 0
for i in b:
    c.append(list(a).index(i,d)+1)
    d += list(a).index(i,d) +1

print(f"The student with average marks above 75 : student{c}")

The student with average marks above 75 : student[1, 3, 5]

# Task 7: Subject-wise Highest Marks.
Find the highest mark obtained in :
* Python
* Maths
* AI

In [398]:
print(f"The highest marks in Python are {marks[:,0].max()}")
print(f"The highest marks in Maths are {marks[:,1].max()}")
print(f"The highest marks in Ai are {marks[:,2].max()}")

The highest marks in Python are 92
The highest marks in Maths are 92
The highest marks in Ai are 95

# Task 8: Add Grace Marks

The Institute gives 5 grace marks to every student in every subject.

Create a new Numpy array containing the upldated marks.

* Important: Do not modify the original marks array

In [399]:
newmarks = marks+5

# Task 9: Apply a Condition
Suppose grace marks connot make a student's marks exceed 100.
Create an updated marks array where:
* if marks+5>100, keep th mark as 100.
* Otherwise, add5

In [400]:
upmarks = marks+5

for i in range (0,len(upmarks)):
    for j in range (0,len(upmarks[0,:])):
        if upmarks[i,j] > 100 :
            upmarks[i,j] = 100

print(upmarks)

[[ 83  90  95]
 [ 70  75  77]
 [ 93  97 100]
 [ 60  65  63]
 [ 97  94  99]]

# Task 10: Pass/Fail Analysis
A student is considered passed if their average marks are 60 or above.

Find:
* Average marks of every student
* Which students passed
* Which students failed
* Number of students who passed
* Number of students who failed

In [401]:
avg_marks = marks.mean(axis = 1)
print(avg_marks)
a = list(avg_marks)
b= 0
c = []
d = []
for i in a:
    if i > 60 :
        c.append(a.index(i,b)+1)
    else:
        d.append(a.index(i,b)+1)
    b+= 1
print(f"Passed students are students{c}")
print(f"Number of passed students is {len(c)}")
print(f"Failed students are students{d}")
print(f"Number of failed students is {len(d)}")

[84.33333333 69.         91.66666667 57.66666667 91.66666667]
Passed students are students[1, 2, 3, 5]
Number of passed students is 4
Failed students are students[4]
Number of failed students is 1

# Task 11: Subject Perforamnce
Find which subject has the highest average marks
Your program should output something like:
* Best performing student :AI
* Average marks:81.8

In [409]:
sub = ["Python","Math","AI"]
mark = list(marks.mean(axis=0))
print(f"Best performing subject: {sub[mark.index(max(mark))]}")
print(f"Average marks: {max(mark)}")

Best performing subject: AI
Average marks: 81.8

# Task 12: Challenge
Find students who satisfy both conditions
* Average marks>75
* And AI marks>90

This forces students to combine two Boolean conditions.

In [ ]:
a = list(marks.mean(axis=1))

# Task 13: Challenge
Calculate the percentage of every student.
Since there are 3 subjects and each is out of 100:
* Total Maximum marks=300

For exampel:
* Percentage=Total marks/300*100

# Task 14 — Final Challenge
Create a performance report using NumPy.
For each student, determine:
* Student 1 → Excellent / Good / Needs Improvement

Use these rules:

* Average	Performance
* ≥ 85	Excellent
* ≥ 70 and < 85	Good
* < 70	Needs Improvement

Do not manually assign the labels. Use NumPy conditions.

# Real-Life Problem
## Suppose we give you  marks of 10 students in an excel file. How you can quickly find the average, highest scorer, students who failed, and subject-wise perforance?

| Name  | Python | Maths | AI |
| ----- | -----: | ----: | -: |
| Aman  |     78 |    85 | 90 |
| Priya |     65 |    70 | 72 |
| Rahul |     88 |    92 | 95 |
| Neha  |     55 |    60 | 58 |
| Arjun |     92 |    89 | 94 |

**Pandas allows Python to work with data like an excel table**

## 2. Import Pandas

In [403]:
### %pip install pandas

In [ ]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

# 3. Create our first DataFrame

In [ ]:
data={
    "Name":["Aman", "Priya", "Rahul", "Neha", "Arjun"],
    "Python":[78,65,88,55,92],
    "Maths":[85,70,92,60,89],
    "AI":[90,72,95,58,94]
}

df=pd.DataFrame(data)

print(df)

    Name  Python  Maths  AI
0   Aman      78     85  90
1  Priya      65     70  72
2  Rahul      88     92  95
3   Neha      55     60  58
4  Arjun      92     89  94

**DataFrame= A Table in Python**

# 4. Understanding the DataFrame

**see the first few rows**

In [ ]:
df.head()

    Name  Python  Maths  AI
0   Aman      78     85  90
1  Priya      65     70  72
2  Rahul      88     92  95
3   Neha      55     60  58
4  Arjun      92     89  94

**see the last few rows**

In [ ]:
df.tail()

    Name  Python  Maths  AI
0   Aman      78     85  90
1  Priya      65     70  72
2  Rahul      88     92  95
3   Neha      55     60  58
4  Arjun      92     89  94

**Number of rows and columns**

In [ ]:
df.shape

(5, 4)

**Column names**

In [ ]:
df.columns

Index(['Name', 'Python', 'Maths', 'AI'], dtype='object')

**Data Types**

In [ ]:
df.dtypes

Name      object
Python     int64
Maths      int64
AI         int64
dtype: object

**Basic Information**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Python  5 non-null      int64
 2   Maths   5 non-null      int64
 3   AI      5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

# Selecting a column

**Single Column**

In [ ]:
df["Python"]

0    78
1    65
2    88
3    55
4    92
Name: Python, dtype: int64

**Multiple Column**

In [ ]:
df[["AI","Python"]]

   AI  Python
0  90      78
1  72      65
2  95      88
3  58      55
4  94      92

### Import Concept
**One pair of brackets==> one column**

**Double Brackets==>multiple columns**

# Selecting Rows

In [ ]:
df.iloc[0]

Name      Aman
Python      78
Maths       85
AI          90
Name: 0, dtype: object

**iloc means select using position**

**First Row**

In [ ]:
df.iloc[0]

Name      Aman
Python      78
Maths       85
AI          90
Name: 0, dtype: object

**Second Row**

In [ ]:
df.iloc[1]

Name      Priya
Python       65
Maths        70
AI           72
Name: 1, dtype: object

**First three Rows**

In [ ]:
df.iloc[0:3]

    Name  Python  Maths  AI
0   Aman      78     85  90
1  Priya      65     70  72
2  Rahul      88     92  95

# 7. Filtering -The most important Part

**"Show me students who scored more than 80 in Python"**

In [ ]:
df[df["Python"]>80]

    Name  Python  Maths  AI
2  Rahul      88     92  95
4  Arjun      92     89  94

# 8. Multiple Conditions

**"Who scored more than 80 in python and maths?"**

In [ ]:
df[(df["Python"]>80)& (df["Maths"]>80)]

    Name  Python  Maths  AI
2  Rahul      88     92  95
4  Arjun      92     89  94

In [ ]:
df[(df["Python"]>80)| (df["Maths"]>80)]

    Name  Python  Maths  AI
0   Aman      78     85  90
2  Rahul      88     92  95
4  Arjun      92     89  94

# 9. Creating a New Column

In [ ]:
df["Total"]=df["Python"]+df["Maths"]+df["AI"]

In [ ]:
df

    Name  Python  Maths  AI  Total
0   Aman      78     85  90    253
1  Priya      65     70  72    207
2  Rahul      88     92  95    275
3   Neha      55     60  58    173
4  Arjun      92     89  94    275

In [ ]:
df["Percentage"]=df["Total"]/3

In [ ]:
df

    Name  Python  Maths  AI  Total  Percentage
0   Aman      78     85  90    253   84.333333
1  Priya      65     70  72    207   69.000000
2  Rahul      88     92  95    275   91.666667
3   Neha      55     60  58    173   57.666667
4  Arjun      92     89  94    275   91.666667

# 11. Basic Statistics

**Average Python Marks**

In [ ]:
df["Python"].mean()

np.float64(75.6)

**Highest**

In [ ]:
df["Python"].max()

92

**Lowest**

In [ ]:
df["Python"].min()

55

In [ ]:
prices*2

array([ 200,  400,  600,  800, 1000])

**Total**

In [ ]:
df["Python"].sum()

np.int64(378)

**Count**

In [ ]:
df["Python"].count()

np.int64(5)

**Complete Numerical Summary-Describe()**

In [ ]:
df.describe()

          Python      Maths        AI       Total  Percentage
count   5.000000   5.000000   5.00000    5.000000    5.000000
mean   75.600000  79.200000  81.80000  236.600000   78.866667
std    15.533834  13.663821  16.22344   45.108757   15.036252
min    55.000000  60.000000  58.00000  173.000000   57.666667
25%    65.000000  70.000000  72.00000  207.000000   69.000000
50%    78.000000  85.000000  90.00000  253.000000   84.333333
75%    88.000000  89.000000  94.00000  275.000000   91.666667
max    92.000000  92.000000  95.00000  275.000000   91.666667

# 11 Missing Values

In [ ]:
data={
    " Name":["Aman","Priya","Rahul","Neha", "Arjun"],
    "Python":[78,65,88,None,92],
    "Math":[85,70,92,60,89],
    "AI":[90,72,95,58,94]
}
df=pd.DataFrame(data)

In [ ]:
df.isnull()

    Name  Python   Math     AI
0  False   False  False  False
1  False   False  False  False
2  False   False  False  False
3  False    True  False  False
4  False   False  False  False

In [ ]:
df.isnull().sum()

 Name     0
Python    1
Math      0
AI        0
dtype: int64

#  12. Handling Missing Values

**Remove rows containing missing values**

In [ ]:
df.dropna()

    Name  Python  Math  AI
0   Aman    78.0    85  90
1  Priya    65.0    70  72
2  Rahul    88.0    92  95
4  Arjun    92.0    89  94

**Or fill the missing values**

In [ ]:
df["Python"]=df["Python"].fillna(df["Python"].mean())

In [ ]:
df

    Name  Python  Math  AI
0   Aman   78.00    85  90
1  Priya   65.00    70  72
2  Rahul   88.00    92  95
3   Neha   80.75    60  58
4  Arjun   92.00    89  94

### Instead of simply deleting the student, we can replace the missing mark with a reasonable value such as the average

# 13. Reading a Real CSV File

**Now move from manually created data to the real dataset**

In [ ]:
df=pd.read_csv("abc.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'abc.csv'

In [ ]:
df

In [ ]:
df.head()

# Mini Project — Student Performance Analyzer

In [ ]:
import pandas as pd

data = {
    "Name": ["Aman", "Priya", "Rahul", "Neha", "Arjun",
             "Simran", "Karan", "Meena"],
    "Python": [78, 65, 88, 55, 92, 74, 61, 85],
    "Maths": [85, 70, 92, 60, 89, 80, 67, 90],
    "AI": [90, 72, 95, 58, 94, 82, 70, 88]
}

df = pd.DataFrame(data)

# Part A — Understanding the Data

## Challenge 1 — Explore the Dataset
Find:
* Number of students
* Number of subjects
* Column names
* Data types of each column

Hint: Think about shape, columns, and dtypes.

## Challenge 2 — Display Students
Display:
* First 5 students
* Last 3 students

Hint: head() and tail()

## Challenge 3 — Select Columns
Display only:
* Student names
* Python marks
* Name and AI marks
* Name, Maths, and AI marks

# Part B — Basic Analysis
## Challenge 4 — Python Performance
Find:
* Average Python marks
* Highest Python marks
* Lowest Python marks
* Total Python marks

## Challenge 5 — Subject-wise Analysis
Find the average marks of all three subjects.

Your output should clearly indicate:

* Python: ?
* Maths: ?
* AI: ?

## Challenge 6 — Find the Top Performer in a Subject
Find:
* Student with the highest Python marks
* Student with the highest Maths marks
* Student with the highest AI marks

Think: You need both the name and the marks.

# Part C — Creating New Information

## Challenge 7 — Total Marks
Create a new column called:
* Total

It should contain the total marks obtained by each student in all three subjects.

## Challenge 8 — Percentage
Create a new column called:
* Percentage

Assume each subject is out of 100.

## Challenge 9 — Average Marks
Create another column:
* Average

It should contain the average marks of each student.

# Part D — Filtering

## Challenge 11 — High Performers
Display students who scored more than 80 in AI.

## Challenge 12 — Multiple Conditions
Display students who:
* scored more than 80 in Python AND more than 80 in Maths.

## Challenge 13 — Find Good Students
Display students whose:
* Average ≥ 70

## Challenge 14 — Find Students Needing Improvement
Display students whose:
* Average < 60

## Challenge 15 — Subject Combination
Find students who satisfy both:
* Python marks ≥ 80
* AND AI marks ≥ 90

# Part F — Final Challenge

## Challenge 16 — Complete Student Report
Create a final DataFrame containing:

* Name
* Python
* Maths
* AI
* Total
* Percentage
* Average
* Performance

The :
* 1. Sort students from highest to lowest percentage.
* 2. Display the top 3 students.
* 3. Display students who need improvement.
* 4. Find the class average percentage.
* 5. Find the highest percentage.
* 6. Find the lowest percentage.